// <auto-generated />
namespace PedidoWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class atualizações_migracao_ftp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizações_migracao_ftp));
        
        string IMigrationMetadata.Id
        {
            get { return "201606141205188_atualizações_migracao_ftp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
