// <auto-generated />
namespace PedidoWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mudancaTipoQuantidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudancaTipoQuantidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201706271810392_mudancaTipoQuantidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
